### ISSUE TITLE
Highlighting issue

### ISSUE THREAD

**Issue by visokoo** [hashicorp/vscode-terraform#121]
Highlighting seems to only work with this syntax:

```
os_profile_linux_config {
    ssh_keys {
      path = "/home/${var.admin_user}/.ssh/authorized_keys"
      key_data = "${var.vm_ssh_key}"
    }
    disable_password_authentication = true
  }
```

Though this is valid syntax for terraform as well and breaks the highlighting:
```
os_profile_linux_config {
    ssh_keys = {
      path = "/home/${var.admin_user}/.ssh/authorized_keys"
      key_data = "${var.vm_ssh_key}"
    }
    disable_password_authentication = true
  }
```
![screen shot 2018-08-15 at 12 43 50 pm](https://user-images.githubusercontent.com/9098149/44169336-ee5f0080-a088-11e8-9e7b-2d40c0ab28d5.png)
![screen shot 2018-08-15 at 12 43 59 pm](https://user-images.githubusercontent.com/9098149/44169339-f0c15a80-a088-11e8-863b-33cb1d731bae.png)

**Comment by robertpeteuil** [comment]
The screenshots look like the language might be set to HCL instead of Terraform.  
- If you have the  [HCL language extension](https://github.com/wholroyd/vscode-hcl) installed it takes ownership of `*.tf` files by default.

The giveaway to me is that references, like `var.admin_user`, are colored in two different colors.
- This isn't possible with the terraform language extension, because the entire string inside `${}` is defined with the same theme selector: "entity.other.attribute-name".  
  - Thus there is no way for a theme to color them differently
- The HCL language extension provides a few more theme selectors.
  - the first element inside `${}` as "storage.modifier.hcl"
  - other elements inside `${}` are defined as "entity.name.type.hcl"

While the HCL extension does provide a bit more customization of syntax highlighting, it has several open issues regarding syntax highlighting.

Here's a quick comparison of a syntax highlighting between the two

Terraform Language
![terraform-language](https://user-images.githubusercontent.com/1554603/50107891-1609d500-01f1-11e9-93b2-b7d27e907fff.png)

HCL Language
![hcl-language](https://user-images.githubusercontent.com/1554603/50107902-1d30e300-01f1-11e9-92ca-0e6efd84f592.png)

**Comment by aeschright** [comment]
Version 2.0+ of the extension handles both of those cases correctly, so I'm going to close this. Thanks!
