### ISSUE TITLE
Incorrect doc link for google_project_iam_member

### ISSUE THREAD

**Issue by RobinsonWM** [hashicorp/vscode-terraform#124]
The doc link for `google_project_iam_member` sends me to https://www.terraform.io/docs/providers/google/r/google_project_iam_member.html, which gives a "Page not found" error.  The correct link is https://www.terraform.io/docs/providers/google/r/google_project_iam.html#google_project_iam_member.

I'm not sure if any others are incorrect; I have found the CTRL+Click links really helpful, and I just happened to notice that specific one was wrong.

**Comment by mauve** [comment]
Thanks for the bug report. The mappings between resource type and document URL is generated based on some heuristics and can be wrong sometimes. I will try and figure out a better way.

**Comment by paultyng** [comment]
The new language server support will include surfacing documentation provided by provider binaries (they will need to be updated to incorporate the docs copy, but it should be happening soon). As such  I don't think we will maintain linking out to docs in the same way since the URLs for those are also migrating with the registry.
