### ISSUE TITLE
Publish new VS Codium release

### ISSUE THREAD

**Issue by torhovland** [hashicorp/vscode-terraform#1263]
### Server Version

```
❯ terraform-ls --version
zsh: command not found: terraform-ls

❯ /Users/tor/.vscode-oss/extensions/hashicorp.terraform-2.20.0-universal/bin/terraform-ls
zsh: exec format error: /Users/tor/.vscode-oss/extensions/hashicorp.terraform-2.20.0-universal/bin/terraform-ls
```

### Terraform Version

```
❯ terraform -v
Terraform v1.3.2
on darwin_arm64

Your version of Terraform is out of date! The latest version
is 1.3.3. You can update by downloading from https://www.terraform.io/downloads.html
```

### Client Version

```
VSCodium v1.72.2
```

### Expected Behavior
No error message.

### Actual Behavior
Error message.

### Steps to Reproduce
1. In VSCodium, install the HashiCorp Terraform extension.
2. It should fail to start.
3. Running `terraform-ls` outside VSCodium should also fail.

**Comment by radeksimko** [comment]
I forgot to mention, that earlier versions, including 2.20.0 had different setting structure/names. The differences are documented here: https://github.com/hashicorp/vscode-terraform/blob/main/docs/settings-migration.md

**Comment by dbanck** [comment]
Hi again,

I'm happy to report that the latest version `2.25.0` of the extension is now available on OpenVSX as well: https://open-vsx.org/extension/hashicorp/terraform. Future versions will be published automatically whenever we release an update.

The extension should work out of the box now and doesn't require additional settings. We also provide a way to auto-migrate your configuration to the latest version. You can remove the `pathToBinary` setting if you like since we now bundle the latest language server version with the extension.

I'm going to close this as resolved for now. However, please feel free to open another issue if you run into any problems upgrading.
