### ISSUE TITLE
Failure to start terraform-ls using Dev Containers Extensions

### ISSUE THREAD

**Issue by dsfrederic** [hashicorp/vscode-terraform#1272]
## Versions
```
v2.24.3
```
### Extension

```
hashicorp.terraform
```

### VS Code

```
Version: 1.73.0 (user setup)
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:34:06.111Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No
```

### Operating System

```
DevContainer in VSCode. Dockerfile is included
```

<details>
  <summary>Docker file</summary>
    Docker file
    ```
    # You can pick any Debian/Ubuntu-based image. 😊
    FROM mcr.microsoft.com/devcontainers/base:bullseye
    
    COPY library-scripts/*.sh /tmp/library-scripts/
    
    # [Option] Install zsh
    ARG INSTALL_ZSH="true"
    # [Option] Upgrade OS packages to their latest versions
    ARG UPGRADE_PACKAGES="false"
    
    # Install needed packages and setup non-root user. Use a separate RUN statement to add your own dependencies.
    ARG USERNAME=vscode
    ARG USER_UID=1000
    ARG USER_GID=$USER_UID
    RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
        && bash /tmp/library-scripts/common-debian.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" "${UPGRADE_PACKAGES}" "true" "true" \ 
        && apt-get install -y graphviz \
        && apt-get clean -y && rm -rf /var/lib/apt/lists/*
    
    # [Option] Install Azure CLI
    ARG INSTALL_AZURE_CLI="true"
    # [Option] Install Docker CLI
    ARG INSTALL_DOCKER="false"
    # [Choice] Node.js version: none, lts/*, 16, 14, 12, 10
    ARG NODE_VERSION="lts/*"
    ENV NVM_DIR=/usr/local/share/nvm
    ENV NVM_SYMLINK_CURRENT=true \
        PATH=${NVM_DIR}/current/bin:${PATH}
    RUN if [ "${INSTALL_AZURE_CLI}" = "true" ]; then bash /tmp/library-scripts/azcli-debian.sh; fi \
        && if [ "${NODE_VERSION}" != "none" ]; then bash /tmp/library-scripts/node-debian.sh "${NVM_DIR}" "${NODE_VERSION}" "${USERNAME}"; fi \
        && if [ "${INSTALL_DOCKER}" = "true" ]; then \
            bash /tmp/library-scripts/docker-debian.sh "true" "/var/run/docker-host.sock" "/var/run/docker.sock" "${USERNAME}"; \
        else \
            echo '#!/bin/bash\n"$@"' > /usr/local/share/docker-init.sh && chmod +x /usr/local/share/docker-init.sh; \
        fi \
        && rm -rf /var/lib/apt/lists/*
    
    # Install Terraform, tflint, Terragrunt
    ARG TERRAFORM_VERSION=0.12.16
    ARG TFLINT_VERSION=0.8.2
    ARG TERRAGRUNT_VERSION=0.28.1
    RUN bash /tmp/library-scripts/terraform-debian.sh "${TERRAFORM_VERSION}" "${TFLINT_VERSION}" "${TERRAGRUNT_VERSION}" \
        && rm -rf /tmp/library-scripts
    
    ENV SHELL /bin/zsh
    
    ENTRYPOINT [ "/usr/local/share/docker-init.sh" ]
    CMD [ "sleep", "infinity" ]
    
    # [Optional] Uncomment this section to install additional OS packages.
    # RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    #     && apt-get -y install --no-install-recommends <your-package-list-here>
    ```

</details>

### Terraform Version

```
Terraform v0.14.5

Your version of Terraform is out of date! The latest version
is 1.3.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Expected Behavior

Terraform ls server should start

### Actual Behavior

Terraform ls server does not start 

### Additional context
![image](https://user-images.githubusercontent.com/28486949/200582058-e976dad7-c009-442e-97c0-529c8bd40909.png)

```
Launching language server: /home/vscode/.vscode-server/extensions/hashicorp.terraform-2.24.3-linux-x64/bin/terraform-ls 
Failure to start terraform-ls. Please check your configuration settings and reload this window
[Error - 1:43:32 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by dbanck** [comment]
Hi @dsfrederic,

There were some issues with dev containers in the past having the wrong settings by default. For example, the call to `terraform-ls` looks like it is missing the `serve` argument.

We [submitted a patch](https://github.com/devcontainers/features/pull/131) for that in September, which should be a part of the 1.0.5 Terraform dev container release.

If updating the dev container version doesn't work for you, you can manually update your `.devcontainer.json` config to reflect the missing argument, [as described here](https://github.com/hashicorp/vscode-terraform/issues/1220#issuecomment-1233122401).

**Comment by dsfrederic** [comment]
Might be a stupid question but how do you update the terraform dev container version? 

I've update my devcontainer file as described but now i seem to have some issues with port forwarding

**Comment by richardsimko** [comment]
I have the same issue from installing the Terraform plugin fresh on the latest VS Code, no dev containers. It seems to be an issue with the default config adding `-tf-exec=/usr/local/bin/terraform` as an arg to the language server.

**Comment by Alsaxian** [comment]
I keep having the same problem after having followed the `.devcontainer.json` adjustment described in issue [#1220](https://github.com/hashicorp/vscode-terraform/issues/1220), which told me to add 
```
	"settings": {
		"terraform.languageServer.enable": true,
		"terraform.languageServer.args": [
			"serve"
		]
	}
```
to my `.devcontainer.json`. 
Behavior after adding this block and rebuilding my dev container: `terraform-ls` always tried to call `/home/vscode/.vscode-server/extensions/hashicorp.terraform-2.25.0-linux-x64/bin/terraform-ls` WITHOUT `serve`. It seemed that this adjustment had not been taken into account.

I further tried to change the Remote Dev Container settings in VS Code manually over settings -> Remote [Dev Container ..] by adding `serve` in words to `Terraform > Language Server: Args`. Something very strange occurred! If I enter `serve` without "", the settings interface won't refuse it but the word doesn't show up under `Terraform > Language Server: Args` (not being taken into account). If I enter any of "serve", 'serve' or \`serve\`, the word will get accepted and saved but by reloading `terraform-ls` will execute literally the command with "serve" or 'serve' or \`serve\`, which, unsurprisingly, will lead to a failure.

Finally I tried to add this arg by modifying the `settings.json` file with
```
	"terraform.languageServer": {
		"enabled": true,
		"args": ["serve"]
	}
```
This time, when I came back to the settings interface, `serve` appears now under `Terraform > Language Server: Args` without "" or '' or \`\`, which makes the whole tool work after reloading the window!

My guess is, `serve` might belong to some VS Code settings key words so that you can run into some parsing errors easily.

I hope this can help you improve the plugin, whether it is a VS Code error or a plugin's.

**Comment by jpogran** [comment]
@dsfrederic either use the provided button when you change the configuration:

![image](https://user-images.githubusercontent.com/272569/203393185-b66d6195-60d9-44ab-a3fa-42a1375e70e9.png)

Or open the Dev Container quick pick using the Command palatte:

![image](https://user-images.githubusercontent.com/272569/203393289-8b1e5c23-08d4-42d2-a30b-a19599d623e6.png)

Then you can rebuild the container and it should pick up your changed settings.

**Comment by jpogran** [comment]
@richardsimko I'm going to open a new issue with your comment, as it doesn't relate to the Dev Container extension it deserves its own investigation.

**Comment by jpogran** [comment]
@Alsaxian I am not able to reproduce the issue you encounter using those steps:

I created a new dev container using the Azure templates (which are still incorrect, I think HashiCorp will need to reach out again) and saw the incorrect settings.

![image](https://user-images.githubusercontent.com/272569/203394249-8a68c390-3eec-4e72-ab6c-09cc07031462.png)

I then opened the devcontainer.json and edited the file:

![image](https://user-images.githubusercontent.com/272569/203394445-68b43cb9-ef16-45de-b6c0-46ccfa46575b.png)

Note in the screenshot I did not include args. I did try both ways and it worked, but suggest omitting args since you are having troubles. In the screenshot I did not include args because "serve" is the default setting, you should only have to set it if you want to add extra arguments.

Then issued a rebuild:

![image](https://user-images.githubusercontent.com/272569/203394297-f462222b-e02b-460a-beb4-668e11e7644c.png)

And after a reload, it shows a successfull start:

![image](https://user-images.githubusercontent.com/272569/203394025-9a76e3fc-6aad-46d6-8351-f0ccbcb38574.png)

If you are still encountering a problem, can you open an issue just for yourself with which dev containr you created yours from so we can troubleshoot?

**Comment by dsfrederic** [comment]
@jpogran can you provide your complete .devcontainer folder? This way I can try and use your configuration

**Comment by dsfrederic** [comment]
@jpogran can you tell me if the TF_BACKEND variables are still supported? For it's not working and I cannot seem to find the related documentation...
