### ISSUE TITLE
Missing some highlighting when making a reference to an undeclared variable 

### ISSUE THREAD

**Issue by lucaspierru-convelio** [hashicorp/vscode-terraform#1372]
### Extension

```
v2.25.4
```

### VS Code

```
v1.76.2
```

### Operating System

```
Linux 5.19.0-38-generic #39-Ubuntu SMP PREEMPT_DYNAMIC x86_64 x86_64 x86_64 GNU/Linux
```

### Terraform Version

```
v1.3.6
```

### Steps To Reproduce
Make a reference to any local or variable that isn't declared and defined, may it be in the same file or another.

### Expected Behavior
There should be syntax highlighting to show that it makes reference to a variable that isn't declared and defined.

### Actual Behavior
It is highlighted as if the variable referenced was existing (light blue).
 
![image](https://user-images.githubusercontent.com/128392693/229846959-3960a26d-acdf-4248-aca6-c32f0f2d7382.png)

### Additional context
Ask if needed but it happens for me in every TF project.

**Comment by lucaspierru-convelio** [comment]
Same issue under VS Code 1.77.2 o 1.77.3

**Comment by radeksimko** [comment]
Hi @lucaspierru-convelio 
While we do provide semantic token based highlighting, which takes valid/invalid references into account, we produce the same token types as the static grammar (that does not take validity into account). In other words, _semantically_ valid references end up _looking_ the same as _syntactically_ valid ones.

You can currently only tell them apart by using the VS Code token inspector.

<img width="479" alt="Screenshot 2023-06-06 at 15 18 12" src="https://github.com/hashicorp/vscode-terraform/assets/287584/3279fb08-6de8-4a90-bf3f-e252f9940041">

![2023-06-06 15 16 58](https://github.com/hashicorp/vscode-terraform/assets/287584/7a227400-fa25-4299-a286-65edb1ab4391)

This is all assuming default VS Code themes. It is possible for anyone to create a Terraform-specific theme which reflects the various token types we produce, as per https://github.com/hashicorp/terraform-ls/blob/main/docs/syntax-highlighting.md#custom-theme-support

One reason it is currently implemented this way is because the language server (which provides the semantic highlighting) does not yet support the whole Terraform language and it could be confusing for the user to see parts of valid configuration mis-highlighted just because it's not recognised yet. The remaining work on the language support is mostly tracked under https://github.com/hashicorp/vscode-terraform/issues/641 and most issues under https://github.com/hashicorp/terraform-schema/issues

Once the language is covered to a satisfiable level, we can re-open the conversation about what this means for semantic highlighting. I noted some higher-level questions which still need to be answered in https://github.com/hashicorp/terraform-ls/issues/1304

With all that in mind I'm going to close this issue in favour of the linked ones. I hope that makes sense.
