### ISSUE TITLE
Unknown configuration options notification after updating to 2.24.0 and higher

### ISSUE THREAD

**Issue by Acolit-sys** [hashicorp/vscode-terraform#1441]
After updating to every version since 2.24 i have annoying notification after each VS Code launch

`Unknown configuration options: ["experimentalFeatures.prefillRequiredFields" "terraform" "indexing" "ignoreSingleFileWarning"]`

Tried to remove the extension completely, either by gui or from \.vscode\extensions folder, and reinstall but it didn't help
Rollback to 2.23 fixes the issue. Using this extension while connecting VS to wsl Ubuntu 22.04 seems to work fine, no warning notifications. 

VS Code - latest
Extension v2.24+
Windows - latest win11

Can not reproduce it on my other computer on windows 10 22H2 but there was a clean install of a latest VS and extension versions, not the update

**Comment by jpogran** [comment]
Hi @Acolit-sys, I'm sorry you're experiencing this. This is due to your settings (something you set at some point in the past) and not something retained in an extension install (where it would be fixed by uninstalling and reinstalling). This is supported by the warning not appearing in WSL or on another computer, as they don't have the same settings as the original.

In [v2.24.0](https://github.com/hashicorp/vscode-terraform/blob/main/docs/settings-migration.md#settings-migration) we deprecated or renamed several different settings. There is a detailed manual migration explanation in that document for which ones were changed and what they changed to.

If you look at https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence, it explains there are scopes and precedence to settings. When VS Code loads, it uses those rules to determine what setting value is resolved. In one of those places, you have old setting names defined.

In order to fix this, you are going to have to look at each of these locations on the affected computer and remove where it is present.
