### ISSUE TITLE
Terraform fmt hangs

### ISSUE THREAD

**Issue by JaimeHolland** [hashicorp/vscode-terraform#1516]
### Extension Version

v2.26.1

### VS Code Version

Version: 1.79.2 (Universal)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:52.392Z (1 wk ago)
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.5.0

### Operating System

macOS 13.4 (22F66)

### Terraform Version

various

### Steps to Reproduce

1. Make a change to any file
2. Hit save
3. Wait for this to finish... ![Screenshot 2023-06-23 at 12 21 36](https://github.com/hashicorp/vscode-terraform/assets/7072383/25f52d43-78d8-4755-a064-3cd990955a72)
4. After about 30 seconds, it seems stuck, so I hit cancel

### Expected Behavior

Should run in a few seconds - it used to until a couple of days ago, not sure what changed

### Actual Behavior

Seems to hang

### Anything Else?

I do use tfenv.  I seem to have read other issues that indicate that this could be the problem, but I don't know any workarounds

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jpogran** [comment]
We know this has been a frustrating experience and appreciate your understanding while we gathered feedback and examples to diagnose this issue. We've created https://github.com/hashicorp/vscode-terraform/issues/1557 as a central place to see updates on what we are doing to address performance issues in terraform-ls in both the short and long term and pinned it to the repo. We'll be adding more detail there as we implement fixes. As we work on this we'll be recording the content and then closing the individual issues so that everyone has one place to look at instead of searching for individual tickets for updates.

**Comment by jpogran** [comment]
We've released `2.27.2` which contains two fixes (https://github.com/hashicorp/terraform-ls/pull/1369, https://github.com/hashicorp/terraform-ls/pull/1372) in our continuing efforts to address this issue.

With the fix, we should be back to terraform-ls `v0.29.2` levels of CPU usage while maintaining the memory improvements of `v0.29.3`.

If you have the time, please give it a try and let us know how it works for you. Please open a new issue rather than replying here, as this issue has gotten so many replies with different experiences it is hard to process. 

I am going to close this as we're using https://github.com/hashicorp/vscode-terraform/issues/1557 as a central tracking issue, so subscribe to that to see continued updates.
