### ISSUE TITLE
Externally declared locals produce errors

### ISSUE THREAD

**Issue by aboncok** [hashicorp/vscode-terraform#1581]
### Extension Version

v2.28.0

### VS Code Version

Version: 1.83.0 (system setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

### Operating System

Microsoft Windows Version 22H2 (OS Build 19045.3448)

### Terraform Version

Terraform v1.3.4 on windows_amd64

### Steps to Reproduce

Use a local without declaring it in the current folder.

### Expected Behavior

While it is very much welcome if the plugin checks for the declaration of a local, in some cases the local is not declared in the current folder but is provided by - let's say - a master script which is not available to the developers of the child scripts.
In such cases it would be necessary to ignore such errors.

### Actual Behavior

Locals declared outside of the local folder/scripts get marked as an error and I see no way to easily tell VSCode to ignore them.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment]
Hi @aboncok 
Can you expand on the use case with generation?

In general, if values are expected at a later stage, I would assume those to be declared as variables (i.e. `variable` blocks), not local values (`locals`) - that is one of the fundamental design differences and reasons the two concepts even exist alongside each other. Is there a reason you wish to use generated local values rather than generate e.g. `*.tfvars` or `*.tfvars.json` files which would then map against _known_ variable declarations without every developer/module having to make blind assumptions? I think it would also help communicate intentions as variables generally come with type constraints.

You could even go as far as having "example" tfvars files, separate from the "production" ones (not loaded by default), which developers could use to run `plan` locally, just to verify that module isn't fundamentally broken after making changes to it. You could think of it as mock data.

On a semi-related note, I noticed that you're running `2.28.0` and we recently released some fixes (in `2.28.1`), also related to locals. Can you confirm this concern is _not_ related to what we fixed in https://github.com/hashicorp/hcl-lang/pull/330, i.e. can you try upgrading to the latest version?

**Comment by aboncok** [comment]
Hi @radeksimko

I work for one of the major IT companies and the release tool is provided as is. Though I am aware of the var vs local concept, we do use it in our scripts, unfortunately I have no insight into why some decisions had been made, all I know is that we have to use some locals we did not declare ourselves within our scripts.

I updated today and started seeing the errors. VSCode installed 2.28.1 first and I checked whether this was introduced with it or with 2.28.0. Both has it so it was 2.28.0.

**Comment by radeksimko** [comment]
I can't say this use case is something we would explicitly want to support. I understand the difficult situation you are in however, where you may not have the influence to change things, or may not want to.

I think it may still be helpful to (try to) pass the feedback to whoever is responsible for this current design. It may be that the author behind those scripts/tooling is simply unaware of the difficulties this brings downstream - which I'd argue go far beyond just red squiggles in your IDE. I think it makes testing impossible, in turn reducing the quality of the code and/or productivity of all people involved.

All that said, we have previously discussed the possibility of making various validations configurable - I will create an issue to track that feature so we at least formalise the idea and link here for more context.

The best workaround I can offer you right now is to use this option which turns off all validations, except for HCL:

```hcl
"terraform.validation.enableEnhancedValidation": false,
```

You can read more about the difference between enhanced validation and HCL at https://github.com/hashicorp/terraform-ls/blob/main/docs/validation.md

I hope that helps.

**Comment by aboncok** [comment]
Thank you @radeksimko, I'll check that workaround.
I'll try to leave some feedback within my company and might reference this issue.

**Comment by radeksimko** [comment]
I filed https://github.com/hashicorp/vscode-terraform/issues/1605 to follow up on configurable validators and (re)explain the problem there.
