### ISSUE TITLE
Terragrunt files are not recognized anymore with "unexpected attribute" errors

### ISSUE THREAD

**Issue by evertonspader-tomtom** [hashicorp/vscode-terraform#1615]
### Extension Version

v2.28.2

### VS Code Version

Version: 1.82.3 (Universal)
Commit: fdb98833154679dbaa7af67a5a29fe19e55c2b73
Date: 2023-10-02T11:06:17.496Z
Electron: 25.8.1
ElectronBuildId: 24153832
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0

### Operating System

macOS 14.0 Beta (23A5312d)

### Terraform Version

Terraform v1.5.0 on darwin_arm64

### Steps to Reproduce

Create a `terragrunt.hcl` file with a simple configuration

### Expected Behavior

No linting issues should be highlighted about invalid attributes in the Terragrunt HCL configuration files

### Actual Behavior

Any configuration in `terragrunt.hcl` files are not being recognized as a valid HCL configuration and yielding the following error:

```
Unexpected attribute: An attribute named "source" is not expected here Terraform
```

### Terraform Configuration

```terraform
For example, a simple file with just a source like:


terraform {
  source = "/path/to/source/module"
}

All other attributes after it such as `inputs`, `dependency`, `remote_state` also yield the same error.
```

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by radeksimko** [comment]
Hi @evertonspader-tomtom 
We never supported Terragrunt since v2.0.0 (released in June 2020).

However this was probably never _as visible_ with all the existing features until the enhanced validation was introduced.

On a more pragmatic/positive note, we do maintain an [HCL extension](https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL) which provides syntax highlighting - which is likely what you are looking for.

As the name suggests, the Terraform extension focuses exclusively on Terraform and HCL extension focuses on any HCL language (such as Terragrunt language). This is further reflected by the file extensions that are automatically claimed (`*.tf`/`*.tfvars` by Terraform extension vs `*.hcl` by the HCL extension).

What appears to have happened is that you manually associated Terragrunt files with `terraform` language, which is something you should be able to undo (remove from settings) and let the HCL extension handle those Terragrunt files automatically (i.e. no explicit language association should be required).

I hope the above makes sense, let us know if you continue running into issues.

**Comment by evertonspader-tomtom** [comment]
Hi @radeksimko ! Thank you very much for your swift response and explanation. I was not aware of the differences in support of both extensions so thank you for that clarification.

I removed the association of `*.hcl` files with the `terraform` extension and it all seems fine now. It just bugged me that there was no highlights in the `.hcl` files until a few days ago and I've been using both extensions for al long time.
