### ISSUE TITLE
TFC: Add Logout Feature

### ISSUE THREAD

**Issue by eponymz** [hashicorp/vscode-terraform#1640]
### Extension Version

v2.29.0

### Problem Statement

This might be an edge case, however, once logged in to TFC through the extension there is no way to log out/log in to a different account. 

### Expected User Experience

Users should be able to change their account as needed.

### Proposal

Ability to log out of an account and restart the log in process with a different token/account.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by eponymz** [comment]
As some extra information on this one. I tried changing the token in `~/.terraform.d/credentials.tfrc.json` as well as `.terraformrc` and retried the login command from VSCode, but it did not switch the account.

**Comment by radeksimko** [comment]
Hi @eponymz,
While I appreciate the feature request, I'm afraid we are very much limited by VS Code here.

> I tried changing the token in ~/.terraform.d/credentials.tfrc.json as well as .terraformrc and retried the login command from VSCode, but it did not switch the account.

The reason this does not make a difference is because we use the "native" VS Code authentication API which - for better or worse - does not watch for any changes on the filesystem. In other words, the token itself is stored by VS Code itself in its own storage where it stores other secrets.

See more details how to log out in Daniel's comment here: https://github.com/hashicorp/vscode-terraform/issues/1634#issuecomment-1818826184

**Comment by radeksimko** [comment]
We also recently added the instructions to our Readme, so hopefully that becomes more visible now.

https://github.com/hashicorp/vscode-terraform/pull/1642

Since we cannot do much more other than documenting it I'm going to close this issue.
