### ISSUE TITLE
Heredoc causes text cursor to freeze

### ISSUE THREAD

**Issue by Lewis-Globacap** [hashicorp/vscode-terraform#1784]
### Extension Version

v2.30.2024042211

### VS Code Version

Version: 1.83.0
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:13:10.518Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.5.0

### Operating System

macOS Sonoma 14.5 Apple M1

### Terraform Version

Terraform v1.7.3 on darwin_arm64

### Steps to Reproduce

1. Create any terraform resource
2. Create a Heredoc where atleast two lines start with a terraform variable. eg (${var.example})

### Demo
![heredoc-bug](https://github.com/hashicorp/vscode-terraform/assets/145339879/e21fde19-4c7d-46ce-b84b-e3daf5e3bcd4)

### Expected Behavior

VSCode operates as normal no noticable change.

### Actual Behavior

Text cursor stop visibly moving, however it is actually moving and you can update text. 

### Terraform Configuration

```terraform
resource "datadog_monitor" "monitor" {
    name = "Service"
    type = "metric alert"
    query = ""

    message = <<EOF
{{#is_alert}}
${var.environment} DOWN
{{/is_alert}} 

{{#is_alert_recovery}}
${var.environment} Service is UP
{{/is_alert_recovery}} 
EOF
}
```

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @Lewis-Globacap 👋

First of all: Thank you for the awesome demo gif 👍 Well appreciated!

I was able to reproduce your issue on VS Code v1.83.0:
![vscode-1 83 0](https://github.com/hashicorp/vscode-terraform/assets/1112056/dd41953a-3012-4041-8e31-c677f14e66aa)

Is there a reason why you are on that specific version given it's quite a few months old already? I tried a more recent version (1.90.1) and wasn't able to reproduce it:
![vscode-1 90 1](https://github.com/hashicorp/vscode-terraform/assets/1112056/21d1cb6f-50ad-4a60-83d6-aca176fa6c3c)

That said, it is probably something we won't be able to fix on the extension side either as it seems to stem from the VS Code itself since we aren't in control of the cursor 😅

**Comment by Lewis-Globacap** [comment]
Did not realise how many versions behind I was for vs-code. Have updated my version and the issue is now gone. Thanks for testing it. 😁
