### ISSUE TITLE
Extension flagging storage_account_id as "not expected" and storage_account_name required but storage_account_id is deprecated and will be removed with AzureRM provider v5

### ISSUE THREAD

**Issue by dbhaigh** [hashicorp/vscode-terraform#1879]
### Extension Version

v2.34.2024101517 (pre-release)

### VS Code Version

Version: 1.95.2 (system setup)
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

### Operating System

Windows 11 Home Version

### Terraform Version

Terraform v1.9.6

### Steps to Reproduce

Change "storage_account_name  = azurerm_storage_account.dlshedping001.name" to "storage_account_id  = azurerm_storage_account.dlshedping001.id in a resource "azurerm_storage_container" resource block

### Expected Behavior

I expect the change to be accepted w/o being flagged as an error as per thgis warning from ADO

╷
│ Warning: Argument is deprecated
│
│   with azurerm_storage_container.sc-he-dp-uc-uksouth-metastore,
│   on databricks_metastore.tf line 6, in resource "azurerm_storage_container" "sc-he-dp-uc-uksouth-metastore":
│    6:   storage_account_name  = azurerm_storage_account.st-he-dp-uc-uksouth.name
│
│ the `storage_account_name` property has been deprecated in favour of
│ `storage_account_id` and will be removed in version 5.0 of the Provider.
│
╵

### Actual Behavior

storage_account_id is flagged as unexpected, and storage_account_name is listed as being required

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dbanck** [comment]
Thanks for the report! I was able to reproduce the error you're seeing.

`storage_account_id` was added to the Azure provider in 4.9.0. The latest version of the language server shipped with version 4.5.0, so it doesn't know about the new attribute yet.

We bundle the latest provider schema available at the time of the language server and extension release. If new attributes, blocks or resources are introduced since then, we can't automatically reflect them (yet). The next language server release will bundle the updated schema and fix the problem. We apologize for the inconvenience.

In the meantime, when you run `terraform init`, we'll use the appropriate provider schema from disk.

In case you want to learn more about how we handle provider schemes, we have an explainer here: https://github.com/hashicorp/terraform-ls/blob/main/docs/schema.md

**Comment by dbhaigh** [comment]
OK...  

Then, given that my CI/CD pipeline is using AzureRM v4.9.0, I should be Ok in ignoring the error messages from the extension in VSCode, knowing that it will go away with the next release of the extension, and that is it a spurious, red-herring, being generated by the out-of-date language server being used by the extension

**Comment by dbanck** [comment]
@dbhaigh We have released a new version [2.34.0](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.34.0). This updates the schema to the latest version and should fix the validation error. The update should show up automatically in VS Code.

--- 

If you experience any other validation related bug, please let us know via a new issue.
