### ISSUE TITLE
aws_ec2_transit_gateway_vpc_attachment_accepter does not link to the docs

### ISSUE THREAD

**Issue by jkodroff** [hashicorp/vscode-terraform#199]
For some reason, the resource `aws_ec2_transit_gateway_vpc_attachment_accepter` does not link to the Terraform docs like other resources do (including other TGW related resources).  Maybe something to do with the length of the identifier?

**Comment by jkodroff** [comment]
Resource `aws_route53_resolver_endpoint` has the same issue.

**Comment by paultyng** [comment]
The new language server support will include surfacing documentation provided by provider binaries (they will need to be updated to incorporate the docs copy, but it should be happening soon). As such  I don't think we will maintain linking out to docs in the same way since the URLs for those are also migrating with the registry.
