### ISSUE TITLE
Enable Terragrunt support

### ISSUE THREAD

**Issue by tillig** [hashicorp/vscode-terraform#239]
I'm not sure if this is a language server issue, a plugin issue, or maybe a little of both.

[Terragrunt](https://github.com/gruntwork-io/terragrunt) allows some extra directives in HCL files like specifying `remote_state` ([example](https://github.com/gruntwork-io/terragrunt-infrastructure-live-example/blob/master/prod/terragrunt.hcl)).

If HCL is set to be a Terraform document, you get an error if you define `remote_state` - `Blocks of type "remote_state" are not expected here.`

`remote_state` isn't the only thing that gets caught, it's just an example.

It'd be nice if these files could be handled in a way that allows Terragrunt directives to work. By convention they're always called `terragrunt.hcl` so there could be a naming standard set up by which those files are the only ones that get the extra treatment.

Is this the right place to ask for that?

**Comment by konstantin-recurly** [comment]
The same thing is for inputs and terraform.tfvars file
![image](https://user-images.githubusercontent.com/56006844/69263390-370e3f00-0b93-11ea-9582-64427fdfa719.png)

**Comment by MajorBreakfast** [comment]
<img width="576" alt="Screen Shot 2020-01-17 at 08 54 53" src="https://user-images.githubusercontent.com/340142/72594209-35e55e00-3907-11ea-83ce-41162ea13ebf.png">
I'm also running into this problem. It'd be really nice if there was a way to suppress these errors for `.hcl` files.

**Comment by tillig** [comment]
Perhaps there needs to be a different manner of parsing between .hcl and .tf files - like, if it's .tf, parse it as Terraform; but if it's .hcl, allow the more generalized Hashicorp Config Language to work.

**Comment by tillig** [comment]
Looks like PR #265 has an update to stop treating HCL as Terraform.

**Comment by radeksimko** [comment]
Hi folks,
We recently took over and updated the HCL extension, which you can read more about at https://www.hashicorp.com/blog/announcing-the-hcl-extension-for-visual-studio-code-0-1

Given that Terragrunt config files use a naming convention of `terragrunt.hcl`, you can use that extension to highlight these configs. We will eventually likely provide some additional basic functionality for _HCL_ configs (which doesn't require schema and other metadata) via that HCL extension, such as [formatting](https://github.com/hashicorp/vscode-hcl/issues/98).

For any advanced IntelliSense features (completion, hover, etc.), we do not intend to provide that as part of the Terraform extension nor Terraform LS, since Terragrunt has its own schema (own keywords in its config files). However we'd be happy for anyone to create a dedicated Terragrunt extension and/or language server, which claims `terragrunt.hcl`. That allows all extensions to co-exist and each to keep only the necessary scope. A Terragrunt extension can leverage the HCL extension for highlighting (i.e. let it be installed automatically with Terragrunt extension).

As for building out the language server, we maintain https://github.com/hashicorp/hcl-lang which has still experimental (unstable) API, but is designed to be used to build any HCL2-based language server, such as Terragrunt one.
