### ISSUE TITLE
Ignore backend.hcl and .tfilint.hcl

### ISSUE THREAD

**Issue by ryboe** [hashicorp/vscode-terraform#303]
`backend.hcl` is used to set up Terraform Cloud.
`.tflint.hcl` is used to configure `tflint`.

`vscode-terraform` currently flags false positive errors in both of these files. Both of these files should be ignored.

Below is a valid `backend.hcl` file that `vscode-terraform` is complaining about.
<img width="286" alt="backend.hcl errors" src="https://user-images.githubusercontent.com/1250684/79033705-363b7100-7b65-11ea-9dc7-0fd09670791c.png">
<img width="500" alt="image" src="https://user-images.githubusercontent.com/1250684/79033720-52d7a900-7b65-11ea-8974-8493b7c5486c.png">

Here are similar errors from `.tflint.hcl`.
<img width="431" alt="image" src="https://user-images.githubusercontent.com/1250684/79033789-ea3cfc00-7b65-11ea-9b0f-f021bbc479de.png">

**Comment by tillig** [comment]
This seems somewhat related to #239 where again the issue seems to be that more general HCL files are being parsed as though they're specifically Terraform modules.

**Comment by radeksimko** [comment]
Hi folks,
There should no longer be errors or any other diagnostics for either of the two files produced by this extension as it only claims `*.tf` and `*.tfvars` files.

As for backend configuration, we track support of that in https://github.com/hashicorp/vscode-terraform/issues/636 but I would also point out that from [v1.1.0](https://github.com/hashicorp/terraform/blob/v1.1/CHANGELOG.md#110-december-08-2021) it is possible to configure Terraform Cloud via the [new `cloud` block](https://www.terraform.io/cli/cloud/settings#the-cloud-block).

As for tflint support, we intend to integrate via code actions (tracked under https://github.com/hashicorp/vscode-terraform/issues/337 and more broadly under https://github.com/hashicorp/vscode-terraform/issues/635). As for **highlighting** `.tflint.hcl` files you can now use the [HCL extension](https://marketplace.visualstudio.com/items?itemName=HashiCorp.HCL) which we [recently updated](https://www.hashicorp.com/blog/announcing-the-hcl-extension-for-visual-studio-code-0-1). We will eventually likely provide some additional basic functionality for HCL configs (which doesn't require schema and other metadata) via that HCL extension, such as https://github.com/hashicorp/vscode-hcl/issues/98.

For any advanced IntelliSense features (completion, hover, etc.) within tflint config files, we do not intend to provide that as part of the Terraform extension nor Terraform LS, since tflint has its own schema (own keywords in its config files). However we'd be happy for anyone to create a dedicated tflint extension and/or language server, which claims `.tflint.hcl`. That allows all extensions to co-exist and each to keep only the necessary scope. A tflint extension can leverage the HCL extension for highlighting (i.e. let it be installed automatically with tflint extension).

As for building out the language server, we maintain https://github.com/hashicorp/hcl-lang which has still experimental (unstable) API, but is designed to be used to build any HCL2-based language server, such as tflint one.
