### ISSUE TITLE
Upgrading leaves server binary un-executable on macOS Catalina

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vscode-terraform#341]
When the extension downloads new archive and extracts the new binary, it makes the binary un-executable for me and I get the following errors:

```
Launching language server: /Users/radeksimko/.vscode/extensions/hashicorp.terraform-2.0.0-rc.0/lsp/terraform-ls serve
[Error - 5:09:34 PM] Connection to server is erroring. Shutting down server.
[Error - 5:09:34 PM] Connection to server is erroring. Shutting down server.
[Error - 5:09:34 PM] Connection to server is erroring. Shutting down server.
[Error - 5:09:34 PM] Connection to server is erroring. Shutting down server.
```
also see https://github.com/hashicorp/vscode-terraform/issues/329#issuecomment-639565866

I tried to inspect the differences between two binaries (one fresh installed and the one upgraded) and I couldn't find any significant difference, other than timestamp metadata and the fact that one binary is executable and the other one is just getting killed:

```
➜  lsp shasum -a 256 terraform-ls-broken
d0efcfe20817fa857456982662bc37dfed3caaccca0a38ee7fbe688e40c47838  terraform-ls-broken
➜  lsp shasum -a 256 terraform-ls-working
d0efcfe20817fa857456982662bc37dfed3caaccca0a38ee7fbe688e40c47838  terraform-ls-working
➜  lsp xattr -l terraform-ls-broken
➜  lsp xattr -l terraform-ls-working
➜  lsp ls -l terraform-ls-*
-rwxr-xr-x  1 radeksimko  staff  8336048 Jun  5 17:09 terraform-ls-broken
-rwxr-xr-x  1 radeksimko  staff  8336048 Jun  5 17:11 terraform-ls-working
➜  lsp ./terraform-ls-broken -v
[1]    58618 killed     ./terraform-ls-broken -v
➜  lsp ./terraform-ls-working -v
0.3.1
```

My assumption is that it may be getting killed by the System Integrity Protection, but don't have any way of proving it.

**Comment by radeksimko** [comment]
Just confirmed that upgrade from 0.3.1 (which I manually placed in the extension dir) to 0.3.2 went smooth (i.e. the upgrade doesn't produce any un-executable binary anymore in `rc.2`)

**Comment by CallMeLaNN** [comment]
I saw this error after a few auto updates but I just realize it still doesn't even work with v2.0.1 and terraform-ls 0.3.2. So I start digging further...

After comparing new working project and my existing one, actually `terraform.languageServer` settings cause the error. The funny part is VS code doesn't hint the unused settings not even grey it out because this extension have difficulty to run when the server crash.

Actually my project created since early Feb when the language server introduced for TF 0.12. So the `"terraform.indexing" { "enabled": false }` and `"terraform.languageServer": { "enabled": true }` is there for some time.

At first I thought that my issue is similar to some issues reported as you pointed out to here but since it has the same generic error, I just share it.

Maybe I missed something during a few updates but I think silent change in the settings is hard to trace and always being forgotten. Probably it is good for the server to reveal the reason of non 0 exit/unhandled error too.
