### ISSUE TITLE
the extension should allow workspaces with no tf scripts on the root level

### ISSUE THREAD

**Issue by junior** [hashicorp/vscode-terraform#355]
Currently the 2.0.0-rc.2 returns an error if there's no terraform scripts on the root level.

It's common to open the vscode, and the terraform scripts residing on sub-folders.

e.g.:

/
|---/images
|---/terraform
|---/somethingelse

Even if the sub-folder with terraform scripts being previously `terraform init`, the error occurs.

A VSCode Notification with the message:

> "❌ Workspace not initialized. Please run 'terraform ini' in /...". 

And, of course, if you try to `terraform init` on the root level says that is terraform empty.

Error:

```
2020/06/09 12:50:25 exec.go:142: Waiting for command to finish ...
[Error - 12:50:25 PM] Server initialization failed.
  Message: Workspace not initialized. Please run `terraform init` in /Users/xxx/terraform-Playground
  Code: -32098 
2020/06/09 12:50:25 server.go:469: Received 1 new requests
2020/06/09 12:50:25 server.go:165: Processing 1 requests
2020/06/09 12:50:25 server.go:223: Checking request for "shutdown": 
2020/06/09 12:50:25 rpc_logger.go:29: Incoming request for "shutdown" (ID 1): 
2020/06/09 12:50:25 rpc_logger.go:50: Response to "shutdown" (ID 1): null
2020/06/09 12:50:25 server.go:204: Completed 1 requests [214.997µs elapsed]
2020/06/09 12:50:25 server.go:469: Received 1 new requests
2020/06/09 12:50:25 server.go:165: Processing 1 requests
2020/06/09 12:50:25 server.go:223: Checking request for "exit": 
2020/06/09 12:50:25 rpc_logger.go:29: Incoming notification for "exit": 
2020/06/09 12:50:25 schema_storage.go:116: error obtaining schemas: Unable to retrieve schemas: failed to get schemas: Execution of ["terraform" "providers" "schema" "-json"] canceled.
signal: killed
```

Steps to replicate:

- create a folders with files that are not terraform scripts
- create a sub-folder test/terraform with the terraform scripts
- run terraform init on the terraform sub-folder
- open vscode with the `vscode-terraform` extension enabled

**Comment by radeksimko** [comment]
Hi @junior 
Thank you for trying out the new release candidate and providing that early feedback!

You are absolutely right that we should support the setup you described without errors. There are existing issues tracking the work towards solving this:

 - https://github.com/hashicorp/terraform-ls/issues/32 which is about finding the right plugins/schema in case where this isn't in the root of the folder opened in the IDE
 - https://github.com/hashicorp/terraform-ls/issues/106 which is about prompting you to `init` the the UI when appropriate
 - https://github.com/hashicorp/terraform-ls/issues/83 which is about _not erroring_ when you open any folder that doesn't have plugin cache - either because it's genuinely not been `init`'d or because it's just not a Terraform workspace with any `*.tf` files.

Generally speaking this is something we need to solve on the server side, rather than in the extension and I would encourage you to subscribe to the linked issues until we do so.

With that in mind I'm going to close this issue.
