### ISSUE TITLE
autocomplete does not work correctly for the resource type

### ISSUE THREAD

**Issue by andrey-dubnik** [hashicorp/vscode-terraform#373]
Hi,

Having small issues with autocomplete while using the resource block

resource "" "name" {
  
}

Typing anything inside the "" triggers no autocomplete where removing the "" actually triggers the correct behaviour although resource is not quoted

resource helm_release "name" {
  
}

Expected behaviour is to autocomplete inside the quotes of the `resource ""`

**Comment by adubnik** [comment]
It works correctly for the scenario with resource inside the quotes when autocomplete is initiated manually e.g. [Cmd] + [Esc]

**Comment by rothman857** [comment]
I am seeing the same behavior, except that it also does not work correctly with manually initiating autocomplete on windows [ctrl] + [space].

Running v2.0.1 on Windows 10.
VScode 1.46.0

**Comment by paultyng** [comment]
This seems to be a setting/limitation upstream in VS Code: https://github.com/microsoft/vscode/issues/23962#issuecomment-292079416

We'll need to investigate what we can do to override it, until then you will need to manually initiate completion inside quotes.

**Comment by byron70** [comment]
I was able to get this working when manually initiating inside the resource type quotes by adding this to my user settings. I have a feeling adding `"editor.quickSugggestions": {"strings": true}` globally would probably mess with some other languages. 

```    
    "[terraform]": {
        "editor.tabSize": 2,
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "hashicorp.terraform",
        "editor.quickSuggestions": {
            "other": true,
            "comments": false,
            "strings": true
        }
    }
```

**Comment by aeschright** [comment]
Thanks @byron70 – the language-specific config is the best option for people who want to have this option right now.

**Comment by tatsuo48** [comment]
In my case, adding the following improved the situation.
```
"editor.suggest.snippetsPreventQuickSuggestions": false
}
```
After inserting the snippet of the resource, it will be completed without moving the cursor to another line once

**Comment by paultyng** [comment]
Potentially also related to this: https://github.com/microsoft/language-server-protocol/issues/565

We can solve this in a couple ways I think, in order of preference:

1. use the completion item command to trigger an additional completion for the item
2. suggestion the full block instead of the initial keyword (ie. `resource "aws_...."` as the completion item)
3. pass resource names as snippet enums

3 is probably undesirable as you don't get the rich hinting with descriptions, etc. 2 is probably the most "correct" implementation possibly, but 1 is maybe the past of least resistance in the near term.

Here is an implementation of 1 from the Dart extension: https://github.com/Dart-Code/Dart-Code/blob/7df6509870d51cc99a90cf220715f4f97c681bbf/src/providers/dart_completion_item_provider.ts#L197-202
