### ISSUE TITLE
Publish extension on open-vsx.org

### ISSUE THREAD

**Issue by meysholdt** [hashicorp/vscode-terraform#379]
Hi!

Congrats to the 2.0 release! I'm very much looking forward to using it often and hope that I will no longer have bogus syntax validation errors :)

Could you also [publish](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension) your Terraform VS Code Extension on https://open-vsx.org/ ?

This would make it much easier to use the awesome extension in project such as
- [gitpod.io](https://gitpod.io)
- [theia-ide.org](https://theia-ide.org)
- [vscodium.com](https://github.com/VSCodium/vscodium/issues/372)
- [code-server](https://github.com/cdr/code-server)

because the [ToS](https://cdn.vsassets.io/v/M146_20190123.39/_content/Microsoft-Visual-Studio-Marketplace-Terms-of-Use.pdf) doesn't allow those projects to obtain the extension from  Microsoft's marketplace:
> Marketplace Offerings are intended for use only with Visual Studio Products and Services and you may only install and use Marketplace Offerings with Visual Studio Products and Services.

**Comment by paultyng** [comment]
@meysholdt we will take a look at this once we resolve some of the immediate user issues, thanks for the pointer!

**Comment by acim** [comment]
Any progress yet? We are really missing this extension.

**Comment by mattburgess** [comment]
@paultyng would you have any problem with me raising a PR against https://github.com/open-vsx/publish-extensions so that they publish a given extension version to the open-vsx.org repo?

Pro: vscode-terraform maintainers don't need to worry about publishing to open-vsx.org themselves
Con: Latest versions aren't synced automatically; static version numbers are used in https://github.com/open-vsx/publish-extensions/blob/master/extensions.json so a PR is required to get newer versions available in that marketplace. But, again, upstream vscode-terraform maintainers don't need to worry about that, and interested user can raise that trivial PR.

**Comment by mattburgess** [comment]
Uggh. Ignore that comment; I see the open PR now and that's a far better way of doing things.

**Comment by jankeromnes** [comment]
@paultyng Is there any way I can help you publish `vscode-terraform` to https://open-vsx.org? 🙏

Would really love to be able to use this extension in VSCodium, Gitpod, Theia, etc.

**Comment by dbanck** [comment]
I'm happy to report that the latest version `2.25.0` of the extension is now available on OpenVSX as well: https://open-vsx.org/extension/hashicorp/terraform. We also backfilled all the previous versions.

Future versions will be published automatically whenever we release an update.
