### ISSUE TITLE
Issues in 2.x release

### ISSUE THREAD

**Issue by ppanyukov** [hashicorp/vscode-terraform#395]
Everything was working fine. Now the extension auto-updated and *nothing* works. Who make this assumption that the root of my directory is terraform thing? Why can't I disable this "language server"? Formatter doesn't work either. Can't revert to previous working version either.

Total disaster.

**Comment by oliversalzburg** [comment]
See https://github.com/hashicorp/vscode-terraform/issues/366#issuecomment-642763545 for a possible workaround.

**Comment by sorin-costea** [comment]
I'm a bit confused, what does this 2.0.1 version actually DO, I mean part from installing without errors?

**Comment by oliversalzburg** [comment]
@sorin-costea I believe one of the important changes is the improved 0.12 language syntax support.

In the previous version, my entire project file tree was marked red, because VS Code thought every single file had syntax errors. I don't have that anymore, which is nice.

**Comment by sorin-costea** [comment]
@oliversalzburg  you're right, there are no syntax errors marked anymore - because it does nothing 😊 No linting is happening at all just a bit of coloring, and you'll see your errors only when `terraform plan`...

**Comment by FernandoMiguel** [comment]
> @sorin-costea I believe one of the important changes is the improved 0.12 language syntax support.
> 
> In the previous version, my entire project file tree was marked red, because VS Code thought every single file had syntax errors. I don't have that anymore, which is nice.

@oliversalzburg 
the never officially released v1.4 did all that with 0.12 , no issues.
but since it was stuck in a thread on github , not everyone knew about it.

**Comment by oliversalzburg** [comment]
> @oliversalzburg you're right, there are no syntax errors marked anymore - because it does nothing 😊 No linting is happening at all just a bit of coloring, and you'll see your errors only when `terraform plan`...

Yeah, that surely is disappointing. For me the root cause was that I have multiple Terraform projects in my workspace and the extension recognized that as an uninitialized workspace. The comment I quoted above helped me to work around the issue. Now I'm at least able to work again.

There was actually an RC of the 2.0 version of this extension, which I neglected to test :( Now I'm just hoping for quick improvements. Good luck :)

**Comment by sorin-costea** [comment]
@FernandoMiguel I uninstalled 2.0.1 and installed 1.4 from the download file and it still does no linting. Could it be something to be configured on MY side? I never did anything for the 1.3.x they just worked fine (except 0.12 syntax) after install...

**Comment by paultyng** [comment]
@ppanyukov I understand the frustration, we are working to address the outstanding issues, all that said there is no need for the sarcasm and doesn't help the situation or get it fixed any faster.

The downgrading issue is still an upstream VS Code issue. It was just (very) unfortunate timing that they had that bug introduced when we shipped our new version. We never intended that to stop working which is why our release notes and launch blog post both included the standard downgrade instructions.

**Comment by FernandoMiguel** [comment]
> @FernandoMiguel I uninstalled 2.0.1 and installed 1.4 from the download file and it still does no linting. Could it be something to be configured on MY side? I never did anything for the 1.3.x they just worked fine (except 0.12 syntax) after install...

you need tflint (app and vscode ext https://github.com/terraform-linters/tflint ) 
I opened ticket https://github.com/hashicorp/vscode-terraform/issues/337 for that

**Comment by paultyng** [comment]
I don't think there is anything new raised in this issue, the existing ones probably cover it:

- Different folder structures: https://github.com/hashicorp/terraform-ls/issues/32
- Formatting without initialization: https://github.com/hashicorp/terraform-ls/issues/165
- Diagnostic support (red squiggles): https://github.com/hashicorp/terraform-ls/issues/27
