### ISSUE TITLE
Autocomplete when attempting to reference variable in a string not working

### ISSUE THREAD

**Issue by andrewhall209** [hashicorp/vscode-terraform#410]
1.46.1 version - Visual Studio Code - Windows
Terraform Extension version 2.0.1

When attempting to reference a variable as part of a string, autocomplete does not work.

![image](https://user-images.githubusercontent.com/45217744/85333192-02969480-b48e-11ea-938a-349755f04dc3.png)

Also - after referencing the variable, the "# of references" above the variable declaration does not display.

**Comment by radeksimko** [comment]
Hi @andrewhall209 
This is something we plan to implement, but it will be implemented as part of the language server and this issue is the best to keep track of wrt named references in general: https://github.com/hashicorp/terraform-ls/issues/38
I would encourage you to upvote it and/or leave feedback about describing any particular requirements or expectations.

With that in mind I'm going to close this issue in favour of the one linked.
