### ISSUE TITLE
Please add support for formatting .tfvars files

### ISSUE THREAD

**Issue by vfab** [hashicorp/vscode-terraform#426]
The old version of the Terraform extension formatted `.tfvars` files so why doesn't the new version?  Please restore this feature.

Thanks

**Comment by paultyng** [comment]
@radeksimko do you know if this is a limitation in the LS currently or something where the extension is just not sending it?

**Comment by radeksimko** [comment]
Correct, this is a temporary limitation on the LS side where the extension intentionally isn't sending tfvars files to it (yet), because:

1. it doesn't know how to handle it (e.g. figure out the right context in which to provide completion)
2. standardize and document the `languageId` which tfvars should be sent as

Most of the work is tracked under https://github.com/hashicorp/terraform-ls/issues/50 - i.e. I'd love to support it at some point.

I am fairly sure the old extension was interpreting tfvars the same way as `tf` (most other community extensions do), which is wrong because the syntax is not the same.

Relatedly the extension should be treating tfvars differently during syntax highlighting. e.g. I don't think tfvars supports interpolation, function calls, `provider`/`resource`/`data` blocks etc. so these things should not be highlighted there as it gives the user false impression that it is supported. And neither does plain HCL support any of this, which seems to be still highlighted the same way too, giving the same false impression.

**Comment by agaudreault-jive** [comment]
In the meantime, you can configure the file association in VS Code for all `*.tfvars` to `Terraform`. Even if syntax is not the same, the formatting works as I expect in most cases. 

See [Language Identifiers](https://code.visualstudio.com/docs/languages/identifiers) for more info.

**Comment by magnetikonline** [comment]
If anyone is wondering how to write this in your `settings.json` - something like this:

```json
"files.associations": {
	"*.tfvars": "terraform"
},
```
