### ISSUE TITLE
Saving 'main.tf': Running 'HashiCorp Terraform' Formatter hangs.

### ISSUE THREAD

**Issue by dlm69** [hashicorp/vscode-terraform#463]
Since updating VS Code to the latest the Hashicorp Terraform (v2.1.1) autoformat just hangs when saving a terraform file.

vscode:
> Version: 1.48.0 (system setup)
> Commit: db40434f562994116e5b21c24015a2e40b2504e6
> Date: 2020-08-13T07:50:42.600Z
> Electron: 7.3.2
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.19041

![image](https://user-images.githubusercontent.com/55879647/90610967-0d577680-e1fe-11ea-94ab-8310179a0018.png)

terraform ls output:
`2020/08/19 09:23:30 service.go:81: Root modules waiting to be loaded: 0`

**Comment by radeksimko** [comment]
This should be fixed in the latest language server release (0.6.1) via https://github.com/hashicorp/terraform-ls/pull/260

Let us know if you continue having this issue after upgrading.

You should be prompted for an upgrade automatically after relaunching VS Code, unless you point to an explicit location via `pathToBinary`.
