### ISSUE TITLE
Syntax Highlighting Still Broken

### ISSUE THREAD

**Issue by rodrigoechaide** [hashicorp/vscode-terraform#486]
The following block of code still breaks syntax highlighting. If I remove the `=` sign after `config` syntax highlighting goes back to normal. The same happens if I remove the trailing `"` here `key    = "${var.vpc_tf_state_key}/terraform.tfstate"`. This is happening in version 2.2.0, 2.2.1, 2.2.2, and 2.2.3 as well. The latest fixes seem not to fix this specific case.

```terraform
// Modify vpc, subnets and security group data

data "terraform_remote_state" "vpc" {
  backend = "s3"

  config = {
    bucket = var.backend_bucket
    key    = "${var.vpc_tf_state_key}/terraform.tfstate"
    region = var.backend_region
  }
}

data "aws_ssm_parameter" "dev_db_username" {
  name = "/testoapp/dev_db_username"
}

data "aws_ssm_parameter" "dev_db_password" {
  name = "/testapp/dev_db_password"
}

locals {
  // Remove `Name` tag from the map of tags because Elastic Beanstalk generates the `Name` tag automatically
  // and if it is provided, terraform tries to recreate the application on each `plan/apply`
  // `Namespace` should be removed as well since any string that contains `Name` forces recreation
  // https://github.com/terraform-providers/terraform-provider-aws/issues/3963

  name_prefix = "${var.name}${var.delimiter}${var.environment}${var.delimiter}${var.namespace}"
  tags = merge(
    map("Environment", var.environment),
    map("DeployedBy", "terraform"),
    map("Namespace", var.namespace),
    var.tags
  )
}
```

* Syntax Highlighting Broken

![Capture](https://user-images.githubusercontent.com/14820332/91258231-2d41e980-e76c-11ea-8edc-5f093b758e49.PNG)

* Syntax Highlighting Not Broken (After removing `=` sign right after `config`)

![Capture2](https://user-images.githubusercontent.com/14820332/91258282-4e0a3f00-e76c-11ea-8c03-07b21ceabe59.PNG)

**Comment by murillio4** [comment]
Im getting bear ninimum syntax highlighting, no autocomplete and no code validation :/

![image](https://user-images.githubusercontent.com/10120072/92235233-a0a5d280-eeb3-11ea-94a0-58f2ec5704b3.png)
![image](https://user-images.githubusercontent.com/10120072/92235418-efec0300-eeb3-11ea-90d5-e8c40865d961.png)
![image](https://user-images.githubusercontent.com/10120072/92235031-54f32900-eeb3-11ea-8271-f5c70b2d9d5a.png)

Tried to download the latest `terraform-ls` and `terraform-lsp` and using them as language servers instead, but no changes

Never got this plugin to work... Sad that i have to use IntelliJ as an edtitor for Terraform

**Comment by rhanger-halo** [comment]
Syntax highlighting in 2.2.3 **mostly** works for me unlike 2.2.0, but I'm still seeing a few weird things:
1. Interpolation inside strings seems to catch some symbols before the ${, like the dash and forward slash in this example are highlighted blue despite being just a literal character in the string
![image](https://user-images.githubusercontent.com/60523260/92647205-8013b900-f2b5-11ea-8d11-1d5c84c9c602.png)
2. In the example above, the "local" part of local values inside the interpolation is colored orange as though it's interpreted literally, even though it's not.
3. Sometimes resources inside a list are entirely highlighted in blue, but not always?
![image](https://user-images.githubusercontent.com/60523260/92647896-a71eba80-f2b6-11ea-9564-e10181dfae7b.png)

When I remove the list:
![image](https://user-images.githubusercontent.com/60523260/92647958-bdc51180-f2b6-11ea-89cb-5795a4d2de02.png)

4. Also as you can see above, hyphens in resource names seems to break something. I hate using hyphens in resource names anyway, but here we are.

**Comment by pjmiravalle** [comment]
While I don't have an immediate fix for the official Terraform vscode extension, I went ahead and created a vscode extension of my own a while back to solve some syntax highlighting issues of my own: https://marketplace.visualstudio.com/items?itemName=pjmiravalle.terraform-advanced-syntax-highlighting.

I actually just spent my lunch break working through y'alls issues, and wrapped it into v1.1.0 of my extension (which is now live!). I'm working on integrating my code into the official Terraform extension, but in the meantime I highly recommend trying out my extension to see if it solves your syntax highlighting problems. :)

I'll be fairly active on here, and can offer further assistance if you still run into any problems! **Please note that the fixes below are using the Dark+ Visual Studio Code Theme**.

@rodrigoechaide here's how your code looks with my fixes in place:
![image](https://user-images.githubusercontent.com/4603979/93932836-0381d100-fcde-11ea-8bbd-1d2d0f0b0260.png)

@murillio4 here's how your code looks with my fixes in place:
![image](https://user-images.githubusercontent.com/4603979/93932916-1dbbaf00-fcde-11ea-8ea8-35ee25cbf4f2.png)

and finally @rhanger-halo here's how your code looks with my fixes in place:
- Note that I wasn't able to solve the syntax highlighting for resource names that use dashes instead of underscores. I'll have to address this in a separate release (when I have more time!).
![image](https://user-images.githubusercontent.com/4603979/93932971-30ce7f00-fcde-11ea-82d0-e4b32744858e.png)

**Comment by pjmiravalle** [comment]
@rhanger-halo just spent another lunch break working through the remaining issue I brought up yesterday, and I got that working for you as well.

I'm pushing the following features into v1.2.0 of the Terraform Advanced Syntax Highlighting extension now, and I encourage you to check it out! https://github.com/pjmiravalle/vscode-terraform-advanced-syntax-highlighting/releases/tag/v1.2.0
1. Resource names with dashes are now supported
2. Improved the syntax highlighting for negative integers

Here is how your code looks in v1.2.0:
![image](https://user-images.githubusercontent.com/4603979/94051775-45218300-fd95-11ea-8041-a8db3ed4e2d7.png)

**Comment by rodrigoechaide** [comment]
Hi @pjmiravalle, many thanks for the work in this new plugin. I have tried it out and it works like a charm! I also wanted to add that the problem I was having was using Windows as an OS. Now I switched to WSL2 and using just vscode terraform plugin I do not have the syntax highlighting issue anymore. It seems that the issue is related to vscode terraform plugin and windows.

**Comment by pjmiravalle** [comment]
Glad to hear @rodrigoechaide !

**Comment by cmamigonian** [comment]
@pjmiravalle I tried your plugin and it doesn't seem to fix the issue I'm seeing, which is very similar to what @rodrigoechaide was seeing:

![image](https://user-images.githubusercontent.com/33674978/96010635-091b9400-0e10-11eb-9e67-6a666c54de43.png)

The embedded `/${var.cluster_name}` in `"kubernetes.io/cluster/${var.cluster_name}"` is screwing up the quote highlighting.  I noticed after the recent plugin/ls update this problem was introduced.

**Comment by pjmiravalle** [comment]
@cmamigonian thank you for bringing this up. I'll try to replicate this issue when I have some free time next week. I'll keep you posted!

**Comment by cmamigonian** [comment]
@pjmiravalle have you had any time to look into this?

**Comment by pjmiravalle** [comment]
@cmamigonian I unfortunately have not yet, it's been an extremely busy few weeks. I'll keep you posted once I have some free time to dig into this deeper!

**Comment by fishfood34** [comment]
I was having this problem, but then I realized that I have two vs code extensions that were trying to syntax highlight my terraform. HCL extension and the official HashiCorp Terraform extension. VS Code was prioritizing the HCL extension (which has not been updated in a very long time) and when I disabled it this issue was no longer appearing. I recommend that everyone double check that they only have one extension trying to syntax highlight their terraform.

**Comment by jpatrick-ztel** [comment]
@pjmiravalle  are you the only one working on this plugin for that?  If so, take your time!  :-)  

it's totally okay to get busy.  Goodness knows I've been neglecting a few personal project GH PR's for personal apps, that I haven't had time to deal with.

**Comment by sickill** [comment]
I was struggling with this problem for months and I confirm that disabling the HCL extension solves the problem (if your case was similar) 👏

**Comment by jpogran** [comment]
Thank you all for your feedback, and thank you @pjmiravalle for your contributions.

Apologies, I am coming to this ticket after significant time has elapsed since it was created. I've tried to recreate some of the examples here and think that most of them have been covered in releases since this ticket was created and we haven't circled back to this ticket.

I'll try to itemize some of the issues here, but if your report isn't covered please open a new issue with example text I can copy and a screenshot of the syntax highlighting that appears for you.

For everyone watching this ticket, please note @fishfood34's observation about multiple extensions claiming support for Terraform and/or HCL files. VS Code has a non-deterministic evaluation of which extension 'wins' at highlighting a given text file. If you have multiple extensions that claim support for a specific file extension, then it's an almost random chance which one will activate first. The extension that activates first will be able to provide features like syntax highlighting, intellisense and more while the other extensions are either not used at all or will only be able to provide minimal features. You can choose which extension activates for each file by using the `files.associations` setting in VS Code to help decide which extension controls which file.

The original post from @rodrigoechaide I can't reproduce with the current extension, everything after `config` highlights correctly. However I notice there is an incorrect tokenization for `"${var.name}${var.delimiter}${var.environment}${var.delimiter}${var.namespace}"` which I'll create a new issue for.

![image](https://user-images.githubusercontent.com/272569/152013903-f08dbeb0-0ebb-4984-b64c-98217860a1dc.png)

@murillio4 I'm sorry the extension didn't work for you back then. From your screenshot and your explanation, it sounded like you either had a bad install or multiple extensions were claiming support for Terraform files and competing. Can you please install the latest and try again? If you continue to see issues, please open a new issue and let us know.

@rhanger-halo I tried typing out your screenshot, but obviously didn't have all of the text to copy. In your example, `local` is tokenized as a `constant`, so it is highlighted. Both `var` and `local` are highlighted similarly because they're both language constants. I also couldn't reproduce the array list behavior you describe. Can you please install the latest and try again? If you continue to see issues, please open a new issue and let us know.

![image](https://user-images.githubusercontent.com/272569/152014807-a193724e-6b71-4b38-af8e-7ea26a46034c.png)

I'm going to close out this ticket for now. If you have any feedback or encounter any issues, please open a new ticket and we'll address.
