### ISSUE TITLE
Autocomplete does not work for digitalocean resources

### ISSUE THREAD

**Issue by suneg** [hashicorp/vscode-terraform#522]
I've setup the latest version of the plugin, and everything seems to work - with the exception that I get no autocompletion for any digital ocean resources.
<img width="625" alt="Screenshot 2020-11-29 at 10 49 47" src="https://user-images.githubusercontent.com/1258383/100538540-af8cee80-3230-11eb-890d-7d6c136dcde0.png">

Typing `digitalocean_droplet` manually and running `terraform plan` I can verify that the provider is correctly installed (by seing the error below).
<img width="484" alt="Screenshot 2020-11-29 at 10 51 09" src="https://user-images.githubusercontent.com/1258383/100538588-f549b700-3230-11eb-955d-0979b6670cdf.png">

I've tried uninstalling/reinstalling the extension, restarting vscode, performing `terraform init` but without any luck.

I'm not sure if it's broken, unsupported or a user error 😄 

```
Terraform v0.13.5
+ provider registry.terraform.io/digitalocean/digitalocean v2.2.0

hashicorp.terraform extension version: 2.3.0
```

**Comment by suneg** [comment]
I should mention that I'm on:
Mac OS 11.0.1
VS Code: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (2 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

**Comment by paultyng** [comment]
We have started including the latest "Official" provider schemas in the LS builds and we [may be expanding that "Verified"](https://github.com/hashicorp/terraform-ls/issues/321) we just wanted to keep an eye on download size and performance first, but I think it should be included in the next release or two.

Regarding it not picking up the `terraform init`, this is currently an issue that it doesn't pick up an init in an entirely clean directory, but should on a reload, you can track that bug here: https://github.com/hashicorp/terraform-ls/issues/222
