### ISSUE TITLE
Color format broken with new update from 7/1/2021

### ISSUE THREAD

**Issue by Olgoetz** [hashicorp/vscode-terraform#539]
Hi,

in VS Code a resource block looks like this now:

![image](https://user-images.githubusercontent.com/19877252/104092030-8fb20700-5281-11eb-929b-d746c33196ec.png)

The word "resource" is not being formatted with purple any more.
Is there a possibility to adjust this?

I use the One Dark Pro theme and it used to properly work prio to the update

**Comment by radeksimko** [comment]
Hi @Olgoetz 
This change was intentional, so that colours/meanings are aligned with capabilities of semantic highlighting provided by the language server. See https://github.com/hashicorp/vscode-terraform/pull/523 (Grammar Change) for more details and reasoning.

This change looks far more subtle in the default themes. Relatedly the extension, nor language server don't control colours per say (they just assign meanings to certain parts of code), so if you wish to change colour you would need to do so in the theme code.
