### ISSUE TITLE
[HELP] Does this extension support Go To Definition?

### ISSUE THREAD

**Issue by rjinskidepop** [hashicorp/vscode-terraform#564]
It appears from some other issues that this extension does support VSCode Go To Definition [F12] functionality and Find Usage but I'm struggling to get it working.

Does the extension support it? And if so, does it need any more configuration than download, terraform init and load VSCode?

**Comment by radeksimko** [comment]
Hi @rjinskidepop 
This functionality is not yet supported, but it is tracked and will be implemented in the language server which the extension uses:
https://github.com/hashicorp/terraform-ls/issues/95

^ feel free to leave any suggestions for particular use cases there

With that in mind - because there is nothing to be implemented on the extension side - I will close this issue.
