### ISSUE TITLE
Provide an option to disable language server upgrade checks

### ISSUE THREAD

**Issue by willhughes-au** [hashicorp/vscode-terraform#618]
For the the last 10 hours or so, I've been getting repeated notifications to upgrade to 0.16.0 
I'll switch windows, or lock/unlock my machine and again, there will be the prompt. Sometimes several of them. 

"A new langauge server release is availale: 0.16.0. Install now?" 

I don't want to install it. 
I want it to shut up and stop bugging me. I've had to disable the extension just be able to get work done. 

Yesterday it was fine, today something has changed and now it's an incessant pestering. 

Please provide an option to either disable the upgrade checks entirely, or an option to suppress the prompts.

**Comment by glennsarti** [comment]
That seems like an over-reaction. Disabling the entire language server due to an update message?

https://github.com/hashicorp/vscode-terraform/pull/595

Honestly, I think it's a bug

https://github.com/hashicorp/vscode-terraform/blob/main/src/extension.ts#L169-L171

The code says every 24hrs,  but the delay looks wrong.

Should be `1000 x 60 x 60 x 24` 
1000ms in a second
60 seconds in a minute
60 minutes in an hour
24 hours in a day

The current value of  `1000 * 60 * 24` will check every **24 minutes**

**Comment by rockdreamer** [comment]
I got three notifications for the same upgrade that would not go away. In the end, I had to kill the VSCode process tree. Not an over-reaction. It's quite suboptimal UX.

**Comment by aeschright** [comment]
I just put out a patch release that will bring those install attempts down to the intended once a day rate -- thanks to @glennsarti for doing the fix!

We don't have anything in the works right now for letting people skip an update until the next version, which sounds like it would be helpful for some of you. I'd be open to someone doing a PR on that, though, so let us know if you're interested.

**Comment by aeschright** [comment]
One other note: if you want to pin the language server to a particular release and keep the installer from checking for updates, you can [install terraform-ls manually](https://github.com/hashicorp/terraform-ls#installation) and set "pathToBinary" with the full executable path.

**Comment by glennsarti** [comment]
> Not an over-reaction. 

Sorry @rockdreamer I may not have said that correctly.  I meant that it's bad that the workaround for too many updates is to turn off the entire language server.

**Comment by glennsarti** [comment]
@aeschright   I may have a go at a PR to add a "disable update checks" setting.  But I _think_ I can also see some problems with the current implementation which may trip some people up.

**Comment by glennsarti** [comment]
@aeschright   PR is up.

**Comment by lilred** [comment]
Just like everyone else I'm trying to manage the notification spam in my life, so this issue is close to my heart. At this point I'll probably end up ditching `vscode-terraform` over this.

In https://github.com/hashicorp/vscode-terraform/pull/623 @radeksimko writes

>However I feel the `checkForUpdates` is worth further discussion. Partially for the reasons that @aeschright mentioned - i.e. we do not want people to just turn off updates and forget about it, or make it too difficult to turn back on. Updates may contain security patches which are important.

`vscode-terraform` is the only language server I've ever used to nag me about updates multiple times a month. I understand it does slightly more than e.g. OmniSharp but when the description says "syntax highlighting and autocompletion for Terraform" I think most people expect it to slot into their workflow the way a regular language server would.

**Comment by radeksimko** [comment]
@lilred I would be open to a PR which adds a config option to make updates silent and suppress the notifications - would that address your concerns?

**Comment by jpogran** [comment]
We have a similar request reported in https://github.com/hashicorp/vscode-terraform/issues/783. 

In https://github.com/hashicorp/vscode-terraform/pull/868 we configured the extension to silently install the terraform-ls binary without prompting the user. This is currently released in the [preview extension](https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform-preview) if you would like to try this out now. We will be releasing this to [stable](https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform) in the near future.

We are also close to implementing https://github.com/hashicorp/vscode-terraform/issues/820, which will bundle the terraform-ls binary inside the extension, so the extension does not have to download the terraform-ls binary at runtime.

I'm going to lock and close this issue now. Please do open a new issue if the new features we've recently released do not work for you.
