### ISSUE TITLE
Extension launches language servers which will never be used

### ISSUE THREAD

**Issue by JulianCBC** [hashicorp/vscode-terraform#644]
I have a relatively large workspace consisting of several separate somewhat-related projects and only one of these actually contains any Terraform files.

However the Terraform extension loads a separate language server instance for each folder in the workspace, regardless of whether that folder actually contains anything Terraform related.

This is related to but distinct from #627.

I think that these language servers then crawl my entire workspace, find that one Terraform project, then load data for that project which ends up using quite a lot of RAM.

I believe that the solution here is for it to do at least one of:

* Load the language server on-demand as Visual Studio Code encounters Terraform files
* Only auto-load the language server if it sees a `.terraform` directory or `.terraform.lock.hcl` file
* Make sure that the `terraform init` commands are available on all folders, even if the language server isn't loaded, and then load the language server after it's finished.

This issue will be ~80% fixed by fixing #627, however this won't cover the case where Visual Studio Code loads a workspace or folder with no Terraform files in it - I believe that an instance of the language server will be loaded in this case, even though it might never be used.

**Comment by jpogran** [comment]
In https://github.com/hashicorp/terraform-ls/pull/502 we changed the LS to support multiple workspaces with a single LS. In https://github.com/hashicorp/vscode-terraform/pull/845, we changed the client to utilize this change. This should address this issue for you. 

Since this has been open for a long time, I'm going to lock and close this issue now. This is not an indication we are ignoring the issue, but rather an attempt to gauge how recent an issue it is and to gain new diagnostic information. Please do open a new issue if problems persist for you.
