### ISSUE TITLE
Saving '*': Running 'HashiCorp Terraform' Formatter forever

### ISSUE THREAD

**Issue by flavio-cadete-cko** [hashicorp/vscode-terraform#650]
Auto-Format when saving terraform file on Visual Studio Code stopped working after last update.
When I try to close VSCode I get the warning "Waiting for dirty editors to save..."

HashiCorp Terraform v2.11.0
Visual Studio Code v1.56.2

**Comment by radeksimko** [comment]
Hi @flavio-cadete-cko 
Can you check what's the version of the language server installed? It is visible in the log via Output pane:

![Screenshot 2021-05-27 at 14 12 17](https://user-images.githubusercontent.com/287584/119831919-a3d76780-bef5-11eb-8ab1-15cdad58112b.png)

If it's not 0.17.1 - can you please try upgrading and confirm that this is still a problem?

If it is then can you share the whole log from that Output pane (from `Launching language server` until the last line); minus any secrets, please?

**Comment by flavio-cadete-cko** [comment]
Hey @radeksimko , sorry for not responding earlier
![image](https://user-images.githubusercontent.com/51323090/120809854-6486c780-c542-11eb-90a7-22e1f1b40dc5.png)
how I can check that terraform-ls output?

**Comment by roccomuscaritolo-okta** [comment]
I was running into the same issue. Extension version v2.14.0 ( I was not able to find any output or logs. )

I went to the extension configuration and removed everything and reloaded. It seems to be working now.

```
    "terraform.languageServer": {
    
        "external": true,
        "args": [
            "serve"
        ]
    },
```

**Comment by BlackDex** [comment]
Not working for me anymore tried several items like resetting, setting the specific terraform binary manually etc...
It just keeps spinning and spinning and doing nothing.

If i manually start `terraform fmt -recursive` it works fine.

**Comment by jkotchoff** [comment]
+1

**Comment by ocervell** [comment]
+1, auto-formatting doesn't work at all for me.

**Comment by 3abkrino** [comment]
is there any workaround ?

**Comment by kylehutchens** [comment]
Is there any update on this? I am having the same problem where I will restart vscode, formatting will work, like 30 minutes will pass and then I will get "Running 'Hashicorp Terraform' Formatter" forever and nothing goes to the output for Hashicorp Terraform. This only started a couple of weeks ago and is super frustrating. Please help!

**Comment by jpogran** [comment]
Thank you everyone for contributing information to this thread. This is actively being investigated, but it is hard to investigate the problem if no new information is provided. Adding a +1 reaction is helpful in gauging how many people have seen this issue, but not helpful with giving us diagnostic information we need to figure out what is going on.

With the variety of configurations that are possible, it's hard to address each person in a single thread when this is likely situation dependent. We can address each person on an individual basis in individual tickets, where it is much easier to ask each person for needed diagnostic information compared to one long ticket.

For those who responded to this issue, In issue [#542](https://github.com/hashicorp/vscode-terraform/issues/542#issuecomment-1000401937) I outlined some information about how to configure automatic formatting in VS Code. I've ported the relevant parts of my explanation to PR #890 which will update the README with this information. Be sure to read that issue or PR because it outlines information on how to successfully configure the extension to format files. Hopefully that content will help everyone here, if not please open a new issue. When opening a new issue be sure to follow the issue template and include version information, attach logs, config settings and information about the scenario that is occurring.

Since this has been open for a long time, I'm going to lock and close this issue now. This is not an indication we are ignoring the issue, but rather an attempt to gauge how recent an issue it is and to gain new diagnostic information. @flavio-cadete-cko please do open a new issue if problems persist for you.
