### ISSUE TITLE
release 2.13.0 crashing extension service in VSCODE

### ISSUE THREAD

**Issue by abuxton** [hashicorp/vscode-terraform#684]
please see https://github.com/liximomo/vscode-sftp/issues/883#issuecomment-778684682 
When i update VSC to use hashicorp.terraform 2.13 from 2.12.1 i see the issue highlighted above. The extension server crashes out, a downgrade the plugin fixes the problem, and I can switch it back and forth to get the same issue. 

I only upgraded today, and encountered the issue immediately. 

OS = mac big sur 11.3
TF version = Terraform v1.0.0
code --version
1.58.0
2d23c42a936db1c7b3b06f918cde29561cc47cd6
x64

**Comment by radeksimko** [comment]
As discussed privately via Slack, I can't reproduce this issue and it is likely caused by some VS Code internal logic or combination of extensions being installed and active - which would then also lead back to VS Code being unable to deal with any such conflicts between extensions.

Either way I'm happy to reopen and investigate if you can come up with a reliable repro case with a list of extensions that cause the issues or anything like that.
