### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by arvinjarvin** [hashicorp/vscode-terraform#704]
- Issue Type: `Bug`
- Extension Name: `terraform`
- Extension Version: `2.14.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.59.0-insider`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 6529,
		"activateCallTime": 10,
		"activateResolvedTime": 3024,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "hashicorp.terraform",
				"_lower": "hashicorp.terraform"
			},
			"activationEvent": "workspaceContainsTimeout:**/*.tf"
		}
	},
	"runtimeErrors": []
}
```

killing my vscode

**Comment by radeksimko** [comment]
Hi @arvinjarvin 
Do you mind describing some more details about the symptoms (e.g. high CPU or memory usage) and your environment (configuration, number of folders in a workspace, any settings)? Otherwise I'm afraid I'll have to close this issue as there isn't enough details I can act upon and reproduce any problem or address any particular bug.

Also can you open the relevant `Output` pane (`terraform-ls`) and check what version of the language server is being launched? Feel free to paste the whole output from there to a [gist](https://gist.github.com/) and paste the link here.
![Screenshot 2021-07-28 at 07 39 30](https://user-images.githubusercontent.com/287584/127275952-008c64f7-7d3d-48d4-a2a0-ad3e6ba967e7.png)

Thanks.

**Comment by radeksimko** [comment]
Closing for lack of details which would allow us to reproduce the problem.
