### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by dzdiscoveryzone** [hashicorp/vscode-terraform#709]
### My Environment
* macOS Big Sur 11.4
* VSCode 1.58.2

### Extension version: 
* 2.14.0

### Expected behavior
When running the language server and running terraform init I should be getting autocomplete suggestions either automatically or via Cmd + Space

### Actual behavior
Language server loads and starts with no errors, is processing requests however autocomplete does not work.

### Steps to reproduce the issue
1. Reinstall the extension
2. Create brand new directory and at the root add a main.tf with an aws provider
3. Enable the language server (no errors)
4. Terraform init and attempt to create an AWS resource

No suggestions showing:
![image](https://user-images.githubusercontent.com/32343767/127744152-e8981ce6-13bf-4992-8b34-f2d78bea0b59.png)

terraform-ls output:
![image](https://user-images.githubusercontent.com/32343767/127743973-c0a75fd7-281b-41fd-a695-ab2131b34919.png)

**Comment by radeksimko** [comment]
Hi @dzdiscoveryzone 
Based on the folder icon next to `.terraform` in the Explorer panel I'm guessing that you may have at least one another Terraform extension installed.

Can you try disabling any other Terraform extensions, reloading VS Code and tell me if you can still reproduce that?

Relatedly - could you list the names or ideally marketplace URLs for these extensions? I am aware that our users have in the past experienced awkward bugs caused by conflicts with other extensions, see also https://github.com/hashicorp/vscode-terraform/issues/692

**Comment by dzdiscoveryzone** [comment]
Hi @radeksimko,

That was it. I must have installed the HCL extension by wholroyd for color syntax of nomad/hcl jobs. When I uninstalled it, the extension started working. Thanks for your help!
