### ISSUE TITLE
URI "output:extension-output-hashicorp.terraform-%231" is not valid

### ISSUE THREAD

**Issue by ToniCipriani** [hashicorp/vscode-terraform#744]
## Versions

This bug is reproducible in:
 - [X] the **latest** version of the extension (below)
 - [X] the **latest** version of the language server (below)

### Extension

```
Released on
2/12/2016, 03:31:09
Last updated
7/22/2021, 10:24:21
Identifier
hashicorp.terraform
```

### Language Server

```
Output too large, see attached
```
[terraform-ls-debug.out.tar.gz](https://github.com/hashicorp/vscode-terraform/files/7061218/terraform-ls-debug.out.tar.gz)

### VS Code

```
Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z (1 wk ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 19.6.0
```

### Operating System

```
OS X Catalina 10.15.7
Darwin (redacted) 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64 x86_64
```

### Terraform Version

```
Terraform v0.15.3
on darwin_amd64

```

**Comment by radeksimko** [comment]
Just found the root cause. It appears that VS Code consideres `Output` panes as active text editor areas too https://github.com/microsoft/vscode/issues/58869

Which means that if you click/focus on the Output pane and then either the background command runs, or you execute any command yourself (formatting, init, ...) with that pane in focus then we receive URI for that pane, instead of the actual editor tab.

We just need to find a better (more reliable and accurate) way of obtaining the relevant/open file or directory URI...

**Comment by radeksimko** [comment]
I think the best way forward would be looping over `window.visibleTextEditors` and looking for an editor which has `viewColumn == Active` https://code.visualstudio.com/api/references/vscode-api#ViewColumn and relatedly use `vscode.window.onDidChangeVisibleTextEditors` callback instead of `onDidChangeActiveTextEditor`.

I will work on a patch.
