### ISSUE TITLE
Don't nag the user about updates

### ISSUE THREAD

**Issue by mtbambora** [hashicorp/vscode-terraform#783]
## Versions

This bug is reproducible in:
 - [ x] the **latest** version of the extension (below)
 - [ x] the **latest** version of the language server (below)

### Operating System
Find version and build (32-bit or 64-bit) of your OS
 - Windows 10 running WSL (Arch Linux)

### Steps To Reproduce

1. Install Terraform VSCode extension
2. Wait until there is a new update
3. See nagging dialog to update extension

### Expected Behavior
Upgrades should be done silently, like other VSCode extensions

### Actual Behavior
A pop-up appears to nag the user to update
![image](https://user-images.githubusercontent.com/85929494/133967809-15313752-f32b-44eb-beef-c3101f51c62b.png)
 
### Additional context
So often I start VSCode and see this nagging about updating extension. Terraform extension should not nag the user.

**Comment by radeksimko** [comment]
Thank you for the suggestion @mtbambora 

We are considering the idea of bundling the language server with the extension. Silent updates also came up in the past - whether or not we'd still perform updates when we bundle a particular version of LS with the extension remains a question. We will need to consider some trade-offs.

**Comment by radeksimko** [comment]
FWIW there is at least one extension which behaves exactly the same way as ours - https://marketplace.visualstudio.com/items?itemName=golang.Go

I'm not suggesting this is best practice UX, but just to provide some extra data/context.

Generally not all extensions use language servers, but I'd really like us to list some top N popular ones which _do_ use LS and understand how they handle the updates.

**Comment by robdaemon** [comment]
I would be fine with a setting that allows me to turn off the notification, or to only show it when I view a Terraform file. I do a lot of work in VS Code, and only maybe 10% of it is Terraform. This notification pops up more often than I actually make Terraform changes.

**Comment by mtbambora** [comment]
I have the situation as @robdaemon, only Terraform extension asks me to update. An option to disable notification, or even disable checking for updates would work fine. I don't need the latest and greatest.

**Comment by lukasz-mitka** [comment]
I propose providing three options to control update behavior: `silent`, `ask`, `disabled`

**Comment by jpogran** [comment]
I agree that there needs to be an option for the user to decide whether to update the extension/language server or at all, but I disagree it needs to be inside this pop-up window. From personal experience, adding lots of buttons with short names confuses, and adding lots of buttons with long descriptive names makes the box large and distracting.

I propose we honor the existing settings inside VS Code: `extensions.autoCheckUpdates` and `extensions.autoUpdate`. These are built-in settings to the editor that determine whether VS Code updates extensions, or whether it checks for an update at all. If we read these values we can determine if we need to initiate a check or an update without having to have a separate workflow. We can also fully remove the pop-up message entirely, as we know that the user intent is reflected in the settings without having to ask.

This does mean that a user has to disable automatically updating all extensions if they do not want to update ours, but this is the pattern that VS Code wants, so I'm comfortable following it's lead.

**Comment by robdaemon** [comment]
> This does mean that a user has to disable automatically updating all extensions if they do not want to update ours, but this is the pattern that VS Code wants, so I'm comfortable following it's lead.

I have several extensions installed in VS Code, and they update themselves quite regularly. The Terraform extension is the only one that regularly pops up a dialog at VS Code launch asking me to install something else. It's great that the language server components are updated frequently - it really is! But they should be distributed with the plugin instead of this dialog asking for the user to update it.

If this is a pattern this extension will continue to use, I will uninstall this extension.

**Comment by jpogran** [comment]
> But they should be distributed with the plugin instead of this dialog asking for the user to update it.

@robdaemon agreed! We're actually actively researching that, we just haven't created a issue yet. The language specific stuff we provide is in a Golang binary, which is platform specific. We would have to bundle all CPU arch and platforms we support ( 3archs, ~6 different platforms, etc) in the VSIX in order to not download ourselves. That makes the VSIX larger and take longer to extract/install and could trigger a false positive in an AV.

To address this we had several approaches we were working on, but ultimately we were waiting for something called `platform specific extension` to land in VS Code [here](https://github.com/microsoft/vscode/issues/23251#issuecomment-918989339). This requires VS Code v1.60 or greater, so we're figuring out how to be ready when that becomes more mainstream.

In the meantime, I understand your point about the pop-ups and that it behaves differently than VS Code expects. That's why I'm suggesting removing the pop-up question entirely and deciding based on the existing settings you control already. This way, if you have the defaults, you stay consistently updated and are *never* prompted. If you change the default to `false` for either setting, you control the behavior accordingly and are still *never* prompted. The net result is no prompts ever and we behave like other extensions.

**Comment by mtbambora** [comment]
![image](https://user-images.githubusercontent.com/85929494/142829288-acdc550a-aa1a-46ab-853c-2eaf6e21f3a6.png)

**Comment by jpogran** [comment]
In https://github.com/hashicorp/vscode-terraform/pull/868 we configured the extension to silently install the terraform-ls binary without prompting the user. This is currently released in the [preview extension](https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform-preview) if you would like to try this out now. We will be releasing this to [stable](https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform) in the near future.

**Comment by jpogran** [comment]
This has been released in the 2.18.0 version. Please let us know if this works for you!

**Comment by jpogran** [comment]
This has been out for about a month, so this is safe to close now.

We also have recently bundled the terraform-ls binary inside the extension in the [preivew](https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform-preview), which removes the need to download it at all separately. This will be merged to stable soon.
