### ISSUE TITLE
VScode not suggesting for terraform submodule

### ISSUE THREAD

**Issue by roi-ironsrc** [hashicorp/vscode-terraform#796]
Hi 
I am using the latest version of terraform extension.
When I am trying to suggest in the module there is no suggestion by vscode.
for example: 
In module EKS, I am creating node_groups map , and vscode does not suggest parameters...
Any idea? Is it an issue?

**Comment by radeksimko** [comment]
Hi @roi-ironsrc 
Would you mind providing some more details about where exactly do you request the completion and what kind of suggestions you expect there? Can you provide a snippet of code? Also what versions of Terraform, VS Code etc. do you use?

Thanks.

**Comment by roi-ironsrc** [comment]
Hi @radeksimko ,
When I want to write some node groups in the EKS cluster, 
As documented in hashicorp, we need to provide a map of maps with relevant values.
(see the follwing document- [https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest#input_node_groups](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest#input_node_groups)

I will expect from vscode that will provide me suggestions in the node group array...

![image](https://user-images.githubusercontent.com/68992144/134889498-33792765-dae1-4845-aba6-d659829fbc3b.png)


Version terraform  v1.0.6
version vscode hasicorp extenstion - v2.15.0
vscode version 1.6

**Comment by radeksimko** [comment]
Thank you for these extra details.

Unfortunately the extension (or language server to be specific) doesn't have sufficient context to provide any completion for within these maps, because the module input definition doesn't provide it:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/13cb55528c3d931f3aefb092af9f511fe6abd29c/variables.tf#L357-L361

This also applies to the relevant submodule https://github.com/terraform-aws-modules/terraform-aws-eks/blob/13cb55528c3d931f3aefb092af9f511fe6abd29c/modules/node_groups/variables.tf#L49-L53

One way of addressing this would be for the module to leverage objects with predeclared fields instead of `any`. I do not have enough context to suggest exact structure or to tell how difficult would it be to change that particular module, but here is an example:
```hcl
variable "node_groups" {
  type = map(object({
    desired_capacity = number
    max_capacity = number
    min_capacity = number
    additional_tags = map(string)
  }))
}
```
and presumably [all of these fields](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/13cb55528c3d931f3aefb092af9f511fe6abd29c/modules/node_groups/locals.tf#L5-L32) would be declared there.

With that in mind I'm going to close this issue as there isn't any way we can address it here, but I would recommend you to contact the module author/maintainer via GitHub issue and ask them to make adjustments, so that the extension can use such data in the future to provide IntelliSense.
