### ISSUE TITLE
Use VS Code `workspace.fs` for filesystem operations

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vscode-terraform#812]
Follow up to #739 

--- 

## Problem Statement

Currently the extension uses the NodeJS "native" `fs` module to perform filesystem operations.

VS Code API provides [workspace.fs](https://code.visualstudio.com/api/references/vscode-api#FileSystem) for reading and writing files and folders from an uri.

It is possible that using the native VS Code FS API _could_ alleviate some of the FS related issues users have reported, such as https://github.com/hashicorp/vscode-terraform/issues/732

## Expected User Experience

No UX changes expected.

## Proposal

TODO

**Comment by jpogran** [comment]
Since moving to `workspace.fs` in #739, the only place we used the `fs` module that remains is https://github.com/hashicorp/vscode-terraform/blob/b0b2b8ca7e11e1c522d2581e4055cc9c3f99e791/src/serverPath.ts#L55, which attempts to test access to the binary.  This was useful when we were downloading the LS to a folder we might not have permissions to, and is useful now when a user supplies a path to the binary that might be incorrect or inaccessible.

There isn't a direct equivalent method is the `workspace.fs` API, but there is a `stat` method. We could use this to determine if the binary exists, but it would not tell us if we have permission to execute it.
