### ISSUE TITLE
Unable to install Extension 'hashicorp.terraform-2.16.0' as it is not compatible with Code '1.23.1'.

### ISSUE THREAD

**Issue by mkontak** [hashicorp/vscode-terraform#840]
## Versions

This bug is reproducible in:
 - [ ] the **latest** version of the extension (below)
 - [ ] the **latest** version of the language server (below)

### Extension

```

```

### Language Server

```

```

### VS Code

```

```

### Operating System

```

```

### Terraform Version

```

```

**Comment by jpogran** [comment]
Hi @mkontak, thanks for the report. That is correct, the lowest version we support currently is VS Code v1.55. VS Code v1.23 is from [April 2018](https://code.visualstudio.com/updates/v1_23). Due to the way that VS Code is made, if we did not put a lower bound on versions, you could attempt to use the latest version of our extension on an older VS Code version that would fail in an unexpected way without a clear error message.

Did you attempt to install the latest Terraform extension from the Extension Pane in VS Code or from the VS Code Marketplace? They are only supposed to show versions of the extension that are supported by your current install. The only way I know to get the error you did is if you downloaded the VSIX directly and attempted to install from that, which bypasses all the version compatibility checks. Since you didn't fill out any of the fields in the template, it's hard to guess how you got to the current situation.

**Comment by jpogran** [comment]
Since this has been open for a long time, I'm going to lock and close this issue now. Please do open a new issue if problems persist for you.
