### ISSUE TITLE
terraform.codelens.enabled setting doesn't work - "Unknown configuration setting"

### ISSUE THREAD

**Issue by lkolchin** [hashicorp/vscode-terraform#864]
## Versions

This bug is reproducible in:
 - [v2.16.0] the **latest** version of the extension (below)
 - [ ] the **latest** version of the language server (below)

### Extension

```
v2.16.0
```

### Language Server

```

```

### VS Code

```
Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z (2 wks ago)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.5.0
```

### Operating System

```
MacOS Catalina 10.15.5
```

### Terraform Version

```
Terraform v1.0.11
on darwin_amd64
```

**Comment by lkolchin** [comment]
Steps To Reproduce:
1. Go to in ~/Library/Application Support/Code/User/settings.json:

2. Add: 
"terraform.codelens.enabled": false

3. Save and reload

4. Hove over the "terraform.codelens.enabled": false setting and see the "Unknown configuration setting" error

**Comment by radeksimko** [comment]
Hi @lkolchin 
This feature has not shipped yet, but we plan to cut a release very soon, most likely today.

**Comment by radeksimko** [comment]
`2.17.0` was just released, you should be able to use the new settings once you update to that version.

**Comment by lkolchin** [comment]
Sorry @radeksimko but even with the new 2.17.0 version it still shows as "Unknown configuration setting" :(

**Comment by dbanck** [comment]
Sorry for the confusion, @lkolchin. The new setting for toggling displayed reference counts has been released with `2.17.0`, but it's called `terraform.codelens.referenceCount` and can be set to `true` or `false`.

Do you mind explaining why you expected `terraform.codelens.enabled` to work? We renamed the setting at one point during implementation. Did we miss updating the docs somewhere? How can we improve this for future users?

**Comment by lkolchin** [comment]
@dbanck 
So, this setting `terraform.codelens.referenceCount` actually disables references comment but not the codeLens info.
I also want to disable 'Authors' details and when it was committed - https://ibb.co/C5MyYdn
Those comments above resources are visually very annoying and going through the code becomes a struggle.
I already have a CodeLens plugin (and it's not intrusive at all because it shows only when I click on the line).
But your plugin for some reason puts it above the resource code.

Btw, that's where I got the idea for disabling it - https://github.com/hashicorp/vscode-terraform/issues/128#issuecomment-443195805

**Comment by lkolchin** [comment]
@dbanck @radeksimko
Can this issue be re-opened please?
See my comment above.

**Comment by jpogran** [comment]
@lkolchin , thanks for the feedback. The 'authors' detail and other git information is provided either by the internal Git extension in VS Code or the Gitlens extension (if you have that installed). This is not provided by the Terraform extension and not in our control to decide what is displayed.

The CodeLens functionality placement is decided by VS Code, not our extension. This VS Code [issue](https://github.com/Microsoft/vscode/issues/23652#issuecomment-304025993) describes their rationale for not giving an option on placement or display. Unfortunately, that is out of our hands.

The good news is, if you do not want any CodeLens functionality displayed, regardless of which extension is providing it, in any Terraform file right now, you can do so with a language specific editor setting provided by VS Code:

```
"[terraform]": {
  "editor.codeLens": false
},
```

This is a useful way to set editor settings per language, so each extension behaves as you desire without affecting other languages. Using this approach, you can add `git` or other extensions specific codelens settings here to customize what CodeLens functionality is enabled for Terraform files.

Alternately, if you do not want to see any CodeLens for anything ever, you can set the following global setting without a language filter and never see any CodeLens functionality for any extension:

```
"editor.codeLens": false
```

Both the git commit and the issue comment you refer to are from before the extension was maintained by HashiCorp and there has been settings changes since then, so searching through issues from 3 years ago won't be helpful for you. Good news is you don't have to search through commits or issues to find out what settings an extension has.

To get a listing of current settings, you can open the Extensions Pane and navigate to the `HashiCorp Terraform` extension, then click on `Contribution` tab. This shows all commands, settings, and other functionality provided by the extension.

![image](https://user-images.githubusercontent.com/272569/144722973-7559d099-3d86-406e-9a45-164c9fb0b3a5.png)

Alternately, you can open the Settings UI where extension specific settings are shown and see all the settings available for this extension.

![image](https://user-images.githubusercontent.com/272569/144723090-8b3b4356-0bb8-4d58-806c-a43370fc3097.png)

Lastly, if you open the Settings JSON view inside VS Code it will provide autocomplete intellisense for each setting, once you start typing an extension name.

![image](https://user-images.githubusercontent.com/272569/144723109-322748da-56eb-47ad-8f01-bd81ac6b0e1e.png)

**Comment by lkolchin** [comment]
@jpogran - Thanks very much for such a detailed reply.
This is doing exactly what I want now:
```
    "editor.codeLens": true,
    "[terraform]": {
        "editor.codeLens": false
      },
```

Now, just need to talk to the "Setting Toggle" developer to add toggle support to this setting structure :)
```
    "[extension]": {
        "some.setting": false
      },
```
